### ISSUE TITLE
根据 Wiki：Basic-Guide 构建时发生错误

### ISSUE THREAD

**Issue by JingHai-Lingyun** [Light-Beacon/HomepageBuilder#4]
Error Log
```log
(.venv) D:\projects\Python\HomepageBuilder>python main.py -o ./1MainFiles/Project.yml -w ./dist/Custom.xaml
[INFO][Project] Initing ...
[INFO][Project] Loading basic resources
[INFO][Resource] Loading resource pack: D:\projects\Python\HomepageBuilder\Resources
[INFO][Project] Loading plugins
[INFO][Resource] Loading resource pack: D:\projects\Python\HomepageBuilder\Plugin\Markdown\Resources
[INFO][Project] Start to import pack at: ./1MainFiles/Project.yml
[INFO][Project] Pack version: 0.9.0
[INFO][Project] Loading cards
[INFO][Library] Loading library: rootLibrary
Traceback (most recent call last):
  File "D:\projects\Python\HomepageBuilder\main.py", line 28, in <module>
    main()
  File "D:\projects\Python\HomepageBuilder\main.py", line 14, in main
    project = Project(args.open)
              ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Python\HomepageBuilder\Core\Project.py", line 42, in __init__
    self.import_pack(path)
  File "D:\projects\Python\HomepageBuilder\Core\Project.py", line 26, in import_pack
    self.base_library = Library(readYaml(f"{self.base_path}{sep}Libraries{sep}__LIBRARY__.yml"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\Python\HomepageBuilder\Core\Library.py", line 17, in __init__
    for pair in ScanDire(self.location,r'^(?!^__LIBRARY__.yml$).*$'):  # 库所拥有的卡片
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\Python\HomepageBuilder\Core\FileIO.py", line 75, in ScanDire
    output.append((readString(f),filename,exten))
                   ^^^^^^^^^^^^^
  File "D:\projects\Python\HomepageBuilder\Core\FileIO.py", line 11, in readString
    return file.read()
           ^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 10: illegal multibyte sequence
```

**Comment by JingHai-Lingyun** [comment]
另外还有个问题
![image](https://github.com/Light-Beacon/HomepageBuilder/assets/109946426/1c3577ac-e936-47ca-a192-ec959aad8b58)
